[package]
name = "shader-crate"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["dylib", "lib"]

[dependencies]
spirv-std = { version = "0.9" }

[profile.dev]
panic = "unwind"
[profile.release]
panic = "unwind"
